language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-test-dev 
    - libeigen3-dev
    - libtbb-dev

install: 


# Change this to your needs
script: 
 ./waf configure && ./waf