language: cpp

os:
  - linux

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

env:
  global:
    - CI_HOME=`pwd`
  matrix:
    - TBB=ON EIGEN3=ON MPI=ON
    - TBB=ON EIGEN3=ON MPI=OFF
    - TBB=ON EIGEN3=OFF MPI=ON
    - TBB=OFF EIGEN3=ON MPI=ON
    - TBB=OFF EIGEN3=ON MPI=OFF
    - TBB=OFF EIGEN3=OFF MPI=ON
    - TBB=OFF EIGEN3=OFF MPI=OFF

addons:
  apt:
    packages:
    - libboost1.55-all-dev

before_install:
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

install:
  - if [ "$EIGEN3" = "ON" ]; then 'ci/install_eigen.sh' ; fi
  - if [ "$TBB" = "ON" ]; then 'ci/install_tbb.sh' ; fi


# Change this to your needs
script:
  - mpi=""
  - if [ "$MPI" = "OFF" ]; then cpp11="--no-mpi" ; fi
  - ./waf configure $mpi
  - ./waf --tests -v --tests-verbose
