language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-test-dev 
    - libboost-graph-dev 
    - libboost-iostreams-dev l
    - libboost-math-dev
    - libboost-program-options-dev
    - libboost-serialization-dev
    - libboost-system-dev 
    - libboost-thread-dev
    - libeigen3-dev
    - libtbb-dev

install: 


# Change this to your needs
script:
 dpkg -L libboost-serialization1.54-dev 
 ./waf configure && ./waf -v