language: cpp

os:
  - linux

sudo: required

dist: trusty

compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-test-dev
    - libboost-graph-dev
    - libboost-iostreams-dev
    - libboost-math-dev
    - libboost-program-options-dev
    - libboost-serialization-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libboost-filesystem-dev
    - libboost-mpi-dev
    - libboost-regex-dev
    - libeigen3-dev
    - libtbb-dev

install:


# Change this to your needs
script:
  - ./waf configure
  - ./waf --tests=yes -v
