language: cpp

os:
  - linux

sudo: required

dist: trusty

compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libboost1.55-all-dev
    - libeigen3-dev
    - libtbb-dev

install:


# Change this to your needs
script:
  - ./waf configure
  - ./waf --tests -v
